resources:
  - url: http://127.0.0.1:5000/roku-card.js
    type: module
views:
  - cards:
      - type: custom:roku-card
        entity: media_player.office_roku
        tv: true
        apps:
          - app: Netflix
            icon: mdi:netflix
